"""Alert identity and impact are generated by deterministic backend rules."""
class AlertEngine:
    def generate(self,records,congestion,dependencies,risks,weather):
        alerts=[]
        for berth in congestion['berths']:
            impact=[d for d in dependencies if berth['id'] in d['berth_ids']]
            critical=max((d['criticality'] for d in impact),default=0)
            if berth['congestion']>=70 or berth['delay']>=2 or critical>=65:
                dependency=max(impact,key=lambda d:d['criticality']) if impact else None
                alerts.append({'id':'ALERT-'+berth['id'],'severity':'high' if berth['delay']>=3 or berth['congestion']>=85 else 'moderate','type':'combined_infrastructure_congestion','berth_id':berth['id'],'asset_id':dependency['asset_id'] if dependency else None,'vessel_ids':[v['vessel_id'] for v in berth['schedule']],'title':f'Handling capacity at {berth["id"]} is exposing vessel arrivals to delay','problem':f'{berth["name"]} has {berth["capacity"]:g} cargo units/hour of modeled handling capacity against {berth["workload"]:g} scheduled cargo units.','impact':{'congestion':berth['congestion'],'delayHours':berth['delay'],'queue':berth['queue'],'criticality':critical},'timeToImpactHours':min((v['arrival'] for v in berth['schedule'] if v['delay']>0),default=0),'dependency':dependency,'risk':risks.get(dependency['asset_id']) if dependency else None,'source':'backend_rule_over_simulated_port_state'})
        if weather.get('severe'):
            alerts.append({'id':'ALERT-WEATHER','severity':'moderate','type':'weather_exposure','berth_id':None,'asset_id':None,'vessel_ids':[],'title':'External weather forecast crosses configured exposure thresholds','problem':' '.join(weather['severe']),'impact':{},'timeToImpactHours':0,'source':'external_weather_model'})
        return sorted(alerts,key=lambda a:(a['severity']!='high',-a['impact'].get('delayHours',0)))
